@id("190fd761-c572-4aa3-bdea-051dd6273c0b")
@nodeType("SQLNodes:::707")
SELECT
     "S_SUPPKEY" AS "S_SUPPKEY",
     "S_NAME" AS "S_NAME",
     "S_ADDRESS" AS "S_ADDRESS",
     "S_NATIONKEY" AS "S_NATIONKEY",
     "S_PHONE" AS "S_PHONE",
     "S_ACCTBAL" AS "S_ACCTBAL",
     "S_COMMENT" AS "S_COMMENT"
FROM {{ ref('SRC', 'SUPPLIER') }} "SUPPLIER"