@id("6979e7b3-5892-4f67-8401-fdefa13ed740")
@nodeType("35f3d77c-09ca-40f8-9f92-7f2783134ae6")
SELECT
     "L_ORDERKEY" AS "L_ORDERKEY",
     "L_PARTKEY" AS "L_PARTKEY",
     "L_SUPPKEY" AS "L_SUPPKEY",
     "L_LINENUMBER" AS "L_LINENUMBER",
     "L_QUANTITY" AS "L_QUANTITY",
     "L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE",
     "L_DISCOUNT" AS "L_DISCOUNT",
     "L_TAX" AS "L_TAX",
     "L_RETURNFLAG" AS "L_RETURNFLAG",
     "L_LINESTATUS" AS "L_LINESTATUS",
     "L_SHIPDATE" AS "L_SHIPDATE",
     "L_COMMITDATE" AS "L_COMMITDATE",
     "L_RECEIPTDATE" AS "L_RECEIPTDATE",
     "L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT",
     "L_SHIPMODE" AS "L_SHIPMODE",
     "L_COMMENT" AS "L_COMMENT"
FROM {{ ref('SRC', 'LINEITEM') }} "LINEITEM"