@id("11251087-f9ba-4edc-b701-320040653251")
@nodeType("SQLNodes:::707")
SELECT
     "PS_PARTKEY" AS "PS_PARTKEY",
     "PS_SUPPKEY" AS "PS_SUPPKEY",
     "PS_AVAILQTY" AS "PS_AVAILQTY",
     "PS_SUPPLYCOST" AS "PS_SUPPLYCOST",
     "PS_COMMENT" AS "PS_COMMENT"
FROM {{ ref('SRC', 'PARTSUPP') }} "PARTSUPP"